package robotproject;
import htmlgenerator.HtmlGenerator;

public class RobotHtmlGenerator extends HtmlGenerator {

public String getHtml() {

return

html()
	.add(
	head()
		.add(
		meta().setName("description").setContent("Html generated by T2 Datas HtmlGenerator")
		)
		.add(
		meta().setCharset("UTF-8")
		)

	)
	.add(
	body()
		.add(
		div()
			.add(
			p("Heeeej!")
			)
			.add(
			p("Heeeej!")
			)
			.add(
			p("Tjäna!")
			)
			.add(
			p("Tjäna!")
			)
			.add(
			p("Tjäna!")
			)
.setId("div1").setStyle(style().backgroundColor("blue"))
		)
		.add(
		div()
			.add(
			p("Coolio!")
			)
.setId("div2").setStyle(style().backgroundColor("green"))
		)
		.add(
		div()
.setId("div3")
		)
		.add(
		div()
.setId("div4")
		)

	)




.toString();
	}
}
